name: goyai

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Execute tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v6
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v5
    - name: Test
      run: |
        go test -cover -coverprofile=coverage.txt -v .
        bash <(curl -s https://codecov.io/bash) -cF general
